# Generated by Django 4.1.5 on 2023-01-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='battery',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='info',
            name='color',
            field=models.CharField(max_length=20),
        ),
    ]
