# Generated by Django 4.1.5 on 2023-01-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_info_battery_alter_info_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='info',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='battery',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='info',
            name='color',
            field=models.CharField(max_length=30),
        ),
    ]
