# Generated by Django 4.1.5 on 2023-01-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_info_created_at_info_updated_at_alter_info_battery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='runtime',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
