# Generated by Django 4.1.5 on 2023-01-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_info_runtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='firmV',
            field=models.CharField(choices=[('r1m_v2.32', 'r1m_v2.32')], default='r1m_v2.32', max_length=20),
        ),
        migrations.AlterField(
            model_name='info',
            name='color',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
